stages:
  - deploy

deploy:
  stage: deploy
  variables:
    SECURE_FILES_DOWNLOAD_PATH: './.secure_files/'
  script:
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - chmod 600 .secure_files/aws-eb
    # - scp -i .secure_files/.env -o StrictHostKeyChecking=no .secure_files/.env ec2-user@$SERVER_IP:/home/ec2-user/PlannerBuddy-api/.env
    - ssh -o StrictHostKeyChecking=no -i .secure_files/aws-eb ec2-user@$SERVER_IP 'bash -s' < deploy.sh
  only:
    - main